name: 'Golang go.sum'
description: 'Check if the go.mod and go.sum match the source code by running `go mod tidy` and send a Pull Request :rocket:'
author: 'paulvollmer'
branding:
  icon: "check-circle"
  color: "yellow"
runs:
  using: 'composite'
  steps:
    - run: |
        rm -f go.sum
        go mod tidy
        if [[ `git status --porcelain` ]]; then
          if [ -n "$LET_FAIL" ] && [ "$LET_FAIL" != "no" ]; then
            echo "::error file=go.sum::go.mod and go.sum does not match the source code."
            exit 1
          fi
          
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          COMMIT_MSG=${COMMIT_MESSAGE:="chore: go mod tidy"}
          BRANCH=${PR_BRANCH:=go-mod-tidy}
          git checkout -b $BRANCH
          git status
          git add .
          git commit -m "$COMMIT_MSG"
          git log
          git push -u origin $BRANCH

          TITLE=${PR_TITLE:="Update go.sum"}
          BODY=${PR_MESSAGE:="This is a Pull Request generated by [action-golang-gosum](https://github.com://paulvollmer/action-golang-gosum) to update the go.sum file"}
          BASE=${PR_BASE:=master}
          PAYLOAD='{"title": "'$TITLE'", "body": "'$BODY'", "head": "'$BRANCH'", "base": "'$BASE'"}'
          echo $PAYLOAD
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header "Authorization: token $GITHUB_TOKEN" \
          --header 'content-type: application/json' \
          --data "$PAYLOAD"
        fi
      shell: bash
